# Generated by Django 4.2.3 on 2023-10-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnDecrypt', '0002_alter_encryptedfile_encrypted_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedfile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
