# Generated by Django 3.2 on 2023-10-04 14:53

import EnDecrypt.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('EnDecrypt', '0008_alter_encryptedfile_encrypted_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecryptedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decrypted_file', models.FileField(upload_to=EnDecrypt.models.decrypted_file_path)),
                ('decryption_key', models.CharField(max_length=255)),
                ('decrypted_file_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('original_encrypted_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EnDecrypt.encryptedfile')),
            ],
        ),
    ]
