# Generated by Django 4.2.3 on 2023-10-05 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnDecrypt', '0010_encryptedfile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encryptedfile',
            name='user',
        ),
    ]
