# Generated by Django 3.2 on 2023-07-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20230719_0917'),
    ]

    operations = [

    ]
