# Generated by Django 4.2.2 on 2023-07-19 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20230719_0918'),
    ]

    operations = [

    ]
