# Generated by Django 3.2 on 2023-09-22 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_usersession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
