# Generated by Django 3.2 on 2023-07-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_user_date_of_birth'),
    ]

    operations = [

    ]
