# Generated by Django 4.2.3 on 2023-07-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_remove_user_date_of_birth'),
    ]

    operations = [

    ]
