# Generated by Django 4.2.3 on 2023-09-29 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20230922_0635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
