# Generated by Django 3.2 on 2023-07-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
