# Generated by Django 4.2.3 on 2023-10-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stego_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encodedimage',
            name='image',
            field=models.ImageField(upload_to='images/stego/'),
        ),
    ]
