# registration/serializers.py
from rest_framework import serializers
from .models import User


class UserSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = ('email', 'phone_number',
                  'first_name', 'last_name', 'user_id', 'password', 'date_of_birth')
        # As user_id is unique and autogenerated, we don't want it to be writable.
        extra_kwargs = {'user_id': {'read_only': True}}
